import json
import re
import requests

OLLAMA = "http://localhost:11434"
DEFAULT_MODEL = "gemma3:4b"
MAX_WORDS = 60

OLLAMA_HELP = """Ollama is not running (or not installed). On macOS:
  1. Install:      brew install ollama      (or download from https://ollama.com/download)
  2. Start server: ollama serve             (leave it running; the desktop app also starts it)
  3. Get the model: ollama pull gemma3:4b
Then press the button again. Meanwhile a fixed template message is shown instead of Gemma."""

DISCLAIMER_EN = "Not an official warning. Follow DHM and local authorities."
DISCLAIMER_NE = "यो आधिकारिक चेतावनी होइन। DHM र स्थानीय निकायको सूचना पालना गर्नुहोस्।"


class OllamaUnavailable(RuntimeError):
    pass


def _words(t: str) -> int:
    return len(t.split())


def _pick_model() -> str:
    try:
        tags = requests.get(f"{OLLAMA}/api/tags", timeout=3).json().get("models", [])
    except requests.RequestException as e:
        raise OllamaUnavailable(OLLAMA_HELP) from e
    names = [m["name"] for m in tags]
    gem = [n for n in names if "gemma" in n.lower()]
    if not gem:
        raise OllamaUnavailable(f"Ollama is running but no gemma model is installed. Run: ollama pull {DEFAULT_MODEL}")
    return gem[0]


def template_message(district: str, risks: list[dict]) -> dict:
    """Fixed fallback text. Not generated by Gemma."""
    hot = [r for r in risks if r["pct"] >= 50]
    top = max(r["pct"] for r in risks)
    if hot:
        days = ", ".join(f"{r['date'][5:]} ({r['pct']}%)" for r in hot)
        en = (f"In {district}, many forecast rain scenarios cross the level linked to landslides on {days}. Risk may be higher. "
              f"Avoid steep slopes, stream crossings and roads below cuttings, and check before travelling. {DISCLAIMER_EN}")
        ne = (f"{district} मा {days} मा धेरै पूर्वानुमान परिदृश्यमा वर्षा पहिरोसँग जोडिएको सीमा नाघ्छ। जोखिम बढी हुन सक्छ। "
              f"भिरालो ठाउँ, खोला तर्ने ठाउँ र कटानमुनिको बाटो नजिक नजानुहोस्; यात्रा गर्नुअघि बुझ्नुहोस्। {DISCLAIMER_NE}")
    else:
        share_en = "none of the" if top == 0 else f"at most {top}% of the"
        share_ne = "कुनै पनि" if top == 0 else f"बढीमा {top}%"
        en = (f"In {district}, {share_en} forecast rain scenarios cross the level linked to landslides in the next 3 days. "
              f"Risk looks lower, but heavy rain can change this, so stay alert. {DISCLAIMER_EN}")
        ne = (f"{district} मा आउँदो ३ दिन {share_ne} पूर्वानुमान परिदृश्यमा वर्षा पहिरोसँग जोडिएको सीमा नाघ्दैन।" if top == 0 else
              f"{district} मा आउँदो ३ दिन {share_ne} पूर्वानुमान परिदृश्यमा वर्षा पहिरोसँग जोडिएको सीमा नाघ्छ।")
        ne += f" जोखिम कम देखिन्छ, तर भारी वर्षा भए स्थिति फेरिन सक्छ, सतर्क रहनुहोस्। {DISCLAIMER_NE}"
    return {"en": en, "ne": ne, "source": "template", "note": None}


BANNED_EN = ("chance", "probab", "likelihood")  # the percentage is not a landslide probability


def _valid(en: str, calm: bool = False) -> bool:
    """English only: word limit, exact disclaimer, no stray labels, and no wording that turns the scenario share into a landslide chance."""
    if not en or _words(en) >= MAX_WORDS:  # strictly under 60
        return False
    if not en.endswith(DISCLAIMER_EN) or "EN:" in en or "NE:" in en:
        return False
    if calm and any(w in en.lower() for w in ("instabil", "landslide risk is high", "danger", "alert")):
        return False  # every scenario share is under 50%: do not imply danger
    if calm and re.search(r"heavy rain(fall)?( is| are| will be)? (expected|forecast|likely|predicted)|heavy rain(fall)? on", en.lower()):
        return False  # a calm forecast must not announce heavy rain (seen: "Heavy rain is expected on Oct 6 (2.0mm)")
    return not any(w in en.lower() for w in BANNED_EN)


def make_message(district: str, risks: list[dict]) -> dict:
    """Return {en, ne, source, ne_source, note}.
    English: written by Gemma through Ollama and checked by _valid. Nepali: always the fixed template (Gemma's Nepali was
    unreliable in testing). If Ollama is down or Gemma fails the checks, English falls back to the template too and `note`
    explains. Never raises for Ollama being down."""
    base = template_message(district, risks)
    base["ne_source"] = "fixed template"
    try:
        model = _pick_model()
    except OllamaUnavailable as e:
        base["note"] = str(e)
        return base

    facts = "\n".join(
        f"- {r['date']}: {r['pct']}% of {r['n']:,} forecast rain scenarios cross the rainfall level linked to past landslides "
        f"(central forecast rain that day {r['central_rain_mm']} mm)" for r in risks)
    prompt = (
        f"Write a short English message for people living in {district}, Nepal, about landslide risk for the next 3 days, "
        f"to be forwarded on Viber/WhatsApp.\nForecast risk:\n{facts}\n\n"
        f"Rules: plain words, calm tone, no greeting, no fear language, do not say a landslide WILL happen. "
        f"Treat 50% or more of scenarios as higher risk. If every day is under 50%, say clearly that risk looks lower and do NOT mention "
        f"instability, danger or alerts; you may say heavy rain can still change this. The percentage is the share of forecast rain "
        f"scenarios that cross a rain level linked to past landslides. It is NOT the chance, probability or likelihood of a landslide: "
        f"never describe it that way. If risk is higher, say what to do (avoid steep slopes, stream crossings, roads below cuttings). "
        f"The message MUST be under {MAX_WORDS - 5} words and end with exactly: {DISCLAIMER_EN} "
        f"Do not write labels like EN: inside the message.\n"
        f'Reply with JSON only: {{"en": "..."}}'
    )
    for _ in range(3):
        try:
            r = requests.post(f"{OLLAMA}/api/generate", json={
                "model": model, "prompt": prompt, "stream": False, "format": "json",
                "options": {"temperature": 0.3, "num_ctx": 2048}}, timeout=120)
            r.raise_for_status()
            en = str(json.loads(r.json()["response"])["en"]).strip()
        except (requests.RequestException, KeyError, ValueError):
            continue
        if _valid(en, calm=all(x["pct"] < 50 for x in risks)):
            return {**base, "en": en, "source": f"gemma ({model})"}
    base["note"] = ("Gemma did not return an English message that passed the checks (word limit, exact disclaimer, no probability "
                    "wording) after 3 tries; showing the fixed template.")
    return base
