import json
import re
import datetime as dt
import requests

OLLAMA = "http://localhost:11434"
DEFAULT_MODEL = "gemma3:4b"
MAX_WORDS = 60

OLLAMA_HELP = """Ollama is not running (or not installed). On macOS:
  1. Install:      brew install ollama      (or download from https://ollama.com/download)
  2. Start server: ollama serve             (leave it running; the desktop app also starts it)
  3. Get the model: ollama pull gemma3:4b
Then press the button again. Meanwhile a fixed template message is shown instead of Gemma."""

DISCLAIMER_EN = "Not an official warning. Follow DHM and local authorities."
DISCLAIMER_NE = "यो आधिकारिक चेतावनी होइन। DHM र स्थानीय निकायको सूचना पालना गर्नुहोस्।"


class OllamaUnavailable(RuntimeError):
    pass


def _words(t: str) -> int:
    return len(t.split())


def _pick_model() -> str:
    try:
        tags = requests.get(f"{OLLAMA}/api/tags", timeout=3).json().get("models", [])
    except requests.RequestException as e:
        raise OllamaUnavailable(OLLAMA_HELP) from e
    names = [m["name"] for m in tags]
    gem = [n for n in names if "gemma" in n.lower()]
    if not gem:
        raise OllamaUnavailable(f"Ollama is running but no gemma model is installed. Run: ollama pull {DEFAULT_MODEL}")
    return gem[0]


def template_message(district: str, risks: list[dict]) -> dict:
    """Fixed fallback text. Not generated by Gemma."""
    hot = [r for r in risks if r["pct"] >= 50]
    top = max(r["pct"] for r in risks)
    if hot:
        days = ", ".join(f"{r['date'][5:]} ({r['pct']}%)" for r in hot)
        en = (f"In {district}, many forecast rain scenarios cross the level linked to landslides on {days}. Risk may be higher. "
              f"Avoid steep slopes, stream crossings and roads below cuttings, and check before travelling. {DISCLAIMER_EN}")
        ne = (f"{district} मा {days} मा धेरै पूर्वानुमान परिदृश्यमा वर्षा पहिरोसँग जोडिएको सीमा नाघ्छ। जोखिम बढी हुन सक्छ। "
              f"भिरालो ठाउँ, खोला तर्ने ठाउँ र कटानमुनिको बाटो नजिक नजानुहोस्; यात्रा गर्नुअघि बुझ्नुहोस्। {DISCLAIMER_NE}")
    else:
        share_en = "none of the" if top == 0 else f"at most {top}% of the"
        share_ne = "कुनै पनि" if top == 0 else f"बढीमा {top}%"
        en = (f"In {district}, {share_en} forecast rain scenarios cross the level linked to landslides in the next 3 days. "
              f"Risk looks lower, but heavy rain can change this, so stay alert. {DISCLAIMER_EN}")
        ne = (f"{district} मा आउँदो ३ दिन {share_ne} पूर्वानुमान परिदृश्यमा वर्षा पहिरोसँग जोडिएको सीमा नाघ्दैन।" if top == 0 else
              f"{district} मा आउँदो ३ दिन {share_ne} पूर्वानुमान परिदृश्यमा वर्षा पहिरोसँग जोडिएको सीमा नाघ्छ।")
        ne += f" जोखिम कम देखिन्छ, तर भारी वर्षा भए स्थिति फेरिन सक्छ, सतर्क रहनुहोस्। {DISCLAIMER_NE}"
    return {"en": en, "ne": ne, "source": "template", "note": None}


BANNED_EN = ("chance", "probab", "likelihood")  # the percentage is not a landslide probability


def summary_sentence(risks: list[dict]) -> str:
    """The exact sentence the English message must contain. Built from the same numbers the app displays."""
    parts = [f"{dt.date.fromisoformat(r['date']).strftime('%b')} {int(r['date'][8:])} {r['pct']}%" for r in risks]
    return "Forecast rain scenarios crossing the landslide-linked rain level: " + ", ".join(parts) + "."


def _allowed_numbers(risks: list[dict]) -> set[str]:
    ok = {"3", "1000"}
    for r in risks:
        y, mth, d = r["date"].split("-")  # date components are in the data, in padded and unpadded form
        ok.update({y, mth, str(int(mth)), d, str(int(d))})
        mm = f"{r['central_rain_mm']:.1f}"
        ok.update({mm, mm.rstrip("0").rstrip("."), str(int(round(r["central_rain_mm"])))})
    return ok


TOKEN = re.compile(r"\b([A-Z][a-z]{2}) (\d{1,2}) (\d{1,3})%")
SENTENCE = re.compile(r"[^.]*crossing the landslide-linked rain level:[^.]*\.")


def _valid(en: str, risks: list[dict]) -> bool:
    """Word limit, exact disclaimer, and the risk percentages must be exactly the ones the app shows, token by token:
    the same (month, day, percent) entries in the same order, no other percentage anywhere, the key phrase present, and
    nothing outside that sentence may restate the scenarios, use a number that is not in the data, or invert the share."""
    calm = all(r["pct"] < 50 for r in risks)
    if not en or _words(en) >= MAX_WORDS:  # strictly under 60
        return False
    if not en.endswith(DISCLAIMER_EN) or "EN:" in en or "NE:" in en:
        return False
    expected = [(dt.date.fromisoformat(r["date"]).strftime("%b"), str(int(r["date"][8:])), str(r["pct"])) for r in risks]
    if TOKEN.findall(en) != expected or en.count("%") != len(expected):
        return False
    sent = SENTENCE.search(en)
    if not sent or TOKEN.findall(sent.group(0)) != expected:
        return False
    rest = en.replace(sent.group(0), " ").replace(DISCLAIMER_EN, " ")
    low = rest.lower()
    if "%" in rest or "percent" in low or "scenario" in low or any(w in low for w in BANNED_EN):
        return False
    if any(n not in _allowed_numbers(risks) for n in re.findall(r"\d+(?:\.\d+)?", rest)):
        return False
    if re.search(r"\bbelow\b(?! (road )?cuttings)|\bunder\b|\bless than\b|\bfewer\b|\bapproximately\b|\bhalf\b", low):
        return False  # words used to invert or fudge the scenario share (seen: "50% ... are below the rainfall levels")
    if calm and any(w in low for w in ("instabil", "landslide risk is high", "danger", "alert")):
        return False
    if calm and re.search(r"heavy rain(fall)?( is| are| will be)? (expected|forecast|likely|predicted)|heavy rain(fall)? on", low):
        return False
    return True


def make_message(district: str, risks: list[dict]) -> dict:
    """Return {en, ne, source, ne_source, note}.
    English: written by Gemma through Ollama and accepted only if _valid passes (its percentages match the app exactly).
    Nepali: always the fixed template. If Ollama is down or Gemma fails the checks 3 times, English is the template too."""
    base = template_message(district, risks)
    base["ne_source"] = "fixed template"
    try:
        model = _pick_model()
    except OllamaUnavailable as e:
        base["note"] = str(e)
        return base

    s = summary_sentence(risks)
    calm = all(r["pct"] < 50 for r in risks)
    daily = "\n".join(f"- {r['date']}: central forecast rain {r['central_rain_mm']} mm" for r in risks)
    prompt = (
        f"You write a short English message for people in {district}, Nepal, about landslide risk in the next 3 days, for Viber/WhatsApp.\n"
        f"The risk numbers are FIXED and already written for you in this sentence:\n\"{s}\"\n"
        f"Copy that sentence into your message CHARACTER FOR CHARACTER, every word and every percentage, dropping nothing. Do not change, round, reorder, "
        f"explain or add to any number. Do not write any other percentage and do not use the words scenario, scenarios, chance, "
        f"probability or likelihood anywhere else. A higher percentage means more risk, 0% means no scenario crosses the level.\n"
        f"Rain data:\n{daily}\n"
        + ("All percentages are under 50%, so say plainly that risk looks lower. Do not mention instability, danger or alerts, and do not "
           "say heavy rain is expected; you may say heavy rain can still change this.\n" if calm else
           "Percentages of 50% or more mean higher risk: say which days, and say to avoid steep slopes, stream crossings and roads below cuttings.\n")
        + f"Plain calm words, no greeting, never say a landslide WILL happen. The whole message must be under {MAX_WORDS - 8} words "
        f"and end with exactly: {DISCLAIMER_EN}\n"
        f'Reply with JSON only: {{"en": "..."}}'
    )
    for _ in range(3):
        try:
            r = requests.post(f"{OLLAMA}/api/generate", json={
                "model": model, "prompt": prompt, "stream": False, "format": "json",
                "options": {"temperature": 0.2, "num_ctx": 2048}}, timeout=120)
            r.raise_for_status()
            en = str(json.loads(r.json()["response"])["en"]).strip()
        except (requests.RequestException, KeyError, ValueError):
            continue
        if _valid(en, risks):
            return {**base, "en": en, "source": f"gemma ({model})"}
    base["note"] = ("Gemma did not return an English message that passed the checks (its percentages must match the app exactly; "
                    "word limit; exact disclaimer) after 3 tries; showing the fixed template.")
    return base
